apiVersion: v1
kind: Service
metadata:
  name: streamlit-ml-app-service
spec:
  selector:
    app: streamlit-ml-app
  ports:
  - protocol: TCP
    port: 80  # Port exposed to the outside
    targetPort: 8501  # Port inside the container
  type: LoadBalancer  # Exposes the service externally
